[workspace]

members = [
    "crypto",
]

default-members = [
    "crypto",
]

[profile.dev]
panic = "unwind"

[profile.release]
debug = false
panic = "unwind"
debug-assertions = false
codegen-units = 1