[package]
name = "starcoin-crypto"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0" }
libra-crypto = { package="libra-crypto",  git = "https://github.com/libra/libra", rev="76d43b08fd6b42e30fa3792787b8b35308588483" }
scs = { package="starcoin-canonical-serialization", path = "../scs"}
crypto-macro = { package="starcoin-crypto-macro", path = "./crypto-macro"}

[features]
default = []
fuzzing = ["libra-crypto/fuzzing"]