[package]
name = "starcoin-crypto"
version = "0.1.0"
authors = ["Starcoin Core Dev <dev@starcoin.org>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
serde = { version = "1.0" }
libra-crypto = { package="libra-crypto",  git = "https://github.com/starcoinorg/libra", rev="7a35ed6edb7921ab096028aed91b8e5ff11cc74d" }
scs = { package="starcoin-canonical-serialization", path = "../scs"}
crypto-macro = { package="starcoin-crypto-macro", path = "./crypto-macro"}

[features]
default = []
fuzzing = ["libra-crypto/fuzzing"]
